// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {imaging} from '../models';
import {device} from '../models';
import {volume} from '../models';

export function AskAssistant(arg1:number,arg2:string):Promise<void>;

export function AssistantStatus():Promise<main.AssistantStatus>;

export function BackupCurrent():Promise<imaging.Result>;

export function BackupPath():Promise<string>;

export function CancelAssistant():Promise<void>;

export function CancelTransfer():Promise<void>;

export function ChooseImage():Promise<main.ImageInfo>;

export function CloneDevice(arg1:main.CloneOptions):Promise<imaging.Result>;

export function CloseDevice():Promise<void>;

export function EnableWrites(arg1:boolean):Promise<main.DiskInfo>;

export function Environment():Promise<main.Environment>;

export function ExportFile(arg1:number,arg2:string):Promise<string>;

export function ExportTree(arg1:number,arg2:string):Promise<main.ExportResult>;

export function InspectForClone(arg1:string):Promise<main.TrimInfo>;

export function InspectTarget(arg1:string):Promise<main.TargetInfo>;

export function ListDevices():Promise<Array<device.Device>>;

export function ListDir(arg1:number,arg2:string):Promise<Array<volume.Entry>>;

export function OpenDevice(arg1:string):Promise<main.DiskInfo>;

export function OpenImage():Promise<main.DiskInfo>;

export function PreviewFile(arg1:number,arg2:string,arg3:number,arg4:number):Promise<main.Preview>;

export function ResetAssistant():Promise<void>;

export function SetAPIKey(arg1:string):Promise<void>;

export function SetLocale(arg1:string):Promise<void>;

export function UnmountDisk(arg1:string):Promise<void>;

export function WriteImage(arg1:main.WriteRequest):Promise<imaging.Result>;
