// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAssistant(arg1, arg2) {
  return window['go']['main']['App']['AskAssistant'](arg1, arg2);
}

export function AssistantStatus() {
  return window['go']['main']['App']['AssistantStatus']();
}

export function BackupCurrent() {
  return window['go']['main']['App']['BackupCurrent']();
}

export function BackupPath() {
  return window['go']['main']['App']['BackupPath']();
}

export function CancelAssistant() {
  return window['go']['main']['App']['CancelAssistant']();
}

export function CancelTransfer() {
  return window['go']['main']['App']['CancelTransfer']();
}

export function ChooseImage() {
  return window['go']['main']['App']['ChooseImage']();
}

export function CloneDevice(arg1) {
  return window['go']['main']['App']['CloneDevice'](arg1);
}

export function CloseDevice() {
  return window['go']['main']['App']['CloseDevice']();
}

export function EnableWrites(arg1) {
  return window['go']['main']['App']['EnableWrites'](arg1);
}

export function Environment() {
  return window['go']['main']['App']['Environment']();
}

export function ExportFile(arg1, arg2) {
  return window['go']['main']['App']['ExportFile'](arg1, arg2);
}

export function ExportTree(arg1, arg2) {
  return window['go']['main']['App']['ExportTree'](arg1, arg2);
}

export function InspectForClone(arg1) {
  return window['go']['main']['App']['InspectForClone'](arg1);
}

export function InspectTarget(arg1) {
  return window['go']['main']['App']['InspectTarget'](arg1);
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function ListDir(arg1, arg2) {
  return window['go']['main']['App']['ListDir'](arg1, arg2);
}

export function OpenDevice(arg1) {
  return window['go']['main']['App']['OpenDevice'](arg1);
}

export function OpenImage() {
  return window['go']['main']['App']['OpenImage']();
}

export function PreviewFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PreviewFile'](arg1, arg2, arg3, arg4);
}

export function ResetAssistant() {
  return window['go']['main']['App']['ResetAssistant']();
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function SetLocale(arg1) {
  return window['go']['main']['App']['SetLocale'](arg1);
}

export function UnmountDisk(arg1) {
  return window['go']['main']['App']['UnmountDisk'](arg1);
}

export function WriteImage(arg1) {
  return window['go']['main']['App']['WriteImage'](arg1);
}
